trackers:
  hosts:
    office:
      ansible_host: 192.168.1.56
      ansible_user: pi 
    bedroom:
      ansible_host: 192.168.1.57
      ansible_user: pi
    kitchen:
      ansible_host: 192.168.1.58
      ansible_user: pi 
dockers:
  hosts:
    docker2:
      ansible_host: 192.168.0.22
      ansible_user: pcon
    docker:
      ansible_connection: local
      ansible_user: pi 
servers:
  hosts:
    home:
      ansible_host: 192.168.0.5
      ansible_user: ansi
    pihole:
      ansible_host: 192.168.0.20
      ansible_user: pi
glances:
  hosts:
    docker:
    docker2:
    home:
