- hosts: trackers 
  become: true
  become_user: root
  vars_files:
    - credentials.yml
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install needed packages
      apt:
        pkg:
        - build-essential
        - libavahi-compat-libdnssd-dev
        - libsystemd-dev
        - bluetooth
        - libbluetooth-dev
        - libudev-dev
        - libcairo2-dev
        - libpango1.0-dev
        - libjpeg-dev
        - libgif-dev
        - librsvg2-dev
        - vim
        - bluez

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
    - name: Alert completion
      pushover:
        msg: "Trackers updated"
        title: "Ansible"
        app_token: "{{ pushover_token }}"
        user_key: "{{ pushover_user }}"
      delegate_to: localhost
      run_once: true
